### ISSUE TITLE
（前）カードから画像がはみ出る

### ISSUE THREAD

**Issue by YukiNagata-00** [YukiNagata-00/node#206]

**Comment by Aimy-coding** [comment]
done

**Comment by YukiNagata-00** [comment]
ありがとう！！！
結果画面の振り返りカードが若干ものさびし感じになってるから余裕あればそこも修正お願いしたい

<img width="542" alt="スクリーンショット 2023-03-17 0 15 58" src="https://user-images.githubusercontent.com/103622288/225663552-9d4e161a-e4e7-49fc-90f5-0b698cb4de41.png">
