### ISSUE TITLE
選択ゲームのcss追加修正のお願い

### ISSUE THREAD

**Issue by YukiNagata-00** [YukiNagata-00/node#40]
選択ゲームプレイ画面にて以下の点の見た目をFigmaのデザインのように修正していただけますか。現状は画像の通り
・選択肢をクリックした際に表示される　赤、緑のボーダー
・選択肢をクリックした際に表示される　コメント（惜しい！などの）と次の問題へ進むボタン。（「Next」と書いていますが、仮の状態なので変更して大丈夫）
<img width="1440" alt="スクリーンショット 2023-02-16 16 22 38" src="https://user-images.githubusercontent.com/103622288/219296599-a0b97af3-f38c-4ed3-9f93-5d44b3bfb7cb.png">

**Comment by mariescoding** [comment]
了解です！

**Comment by mariescoding** [comment]
メッセージとNextボタンは解決しました。
CorrectとMissのIdやClassがどうなっているのかミーティング中に説明お願いします！！
